export const NETWORKS = ['MTN', 'VODAFONE', 'AIRTELTIGO', 'GLO'];

export const PHONE_REGEX = /^0[0-9]{9}$/;

export const ORDER_STATUS = {
  PENDING: 'PENDING',
  COMPLETED: 'COMPLETED',
  FAILED: 'FAILED',
  REFUNDED: 'REFUNDED'
};

export const DELIVERY_STATUS = {
  PENDING: 'PENDING_DELIVERY',
  PROCESSING: 'PROCESSING',
  DELIVERED: 'DELIVERED',
  FAILED: 'FAILED'
};
